name: Immunity_Box
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  image_picker:
  firebase_auth: ^0.16.1
  firebase_messaging: ^6.0.16
  firebase_storage: ^3.1.6
  firebase_database: ^3.1.6
  shared_preferences:
  getflutter: ^1.0.11
  lottie: ^0.3.4
  fluttertoast: ^4.0.1
  flutter_launcher_icons:


flutter_icons:
  image_path: "images/icon.png"
  android: true
  ios: true

  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/login.png
    - images/start1.png
    - images/awereness.png
    - images/guidance.png
    - images/technology.png
    - images/successStories.png
    - images/coronaBenefits.png
    - images/departmentOfDiseases.png
    - images/aboutApplication.png
    - images/app.png
    - images/Initiative.png
    - images/aboutInitiative.png
    - images/staff1.png
    - images/staff2.png
    - images/staff3.png
    - images/femaleStaff.png
    - images/maleStaff.png
    - images/staff11.png
    - images/cleaningHands.png
    - images/Corona Virus Symptoms Cough.png
    - images/Group 137.png
    - images/clock.png
    - images/hand.png
    - images/Group136.png
    - images/coronavirus (6).png
    - images/No Group Gathering.png
    - images/Don't touch eye.png
    - images/Group 341.png
    - images/Group 171.png
    - images/Group 342.png
    - images/Group 344.png
    - images/No Touching.png
    - images/Group64.png
    - images/lamp.png
    - images/outbreak.png
    - images/chlorine.png
    - images/Group346.png
    - images/Group228.png
    - images/ice.png
    - images/Group344.png
    - images/eye.png
    - images/Group343.png
    - images/Group284.png
    - images/Group285.png
    - images/Group298.png
    - images/Group308.png
    - images/success.png
    - images/benefits.png
    - images/data.json
    - images/pandemic.png
    - images/covid.png
    - images/icon.png



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Cairo
       fonts:
         - asset: fonts/Cairo-Regular.ttf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
